/**
 * Graph command - generates DOT format for Graphviz visualization
 */

import * as fs from 'node:fs';
import { parseToStory, type Story, type StoryNode, type Edge } from '@storygraph/core';

export interface GraphOptions {
  output?: string | undefined;
  layout?: 'TB' | 'LR' | 'BT' | 'RL' | undefined;
}

/**
 * Generate a DOT graph representation of a story.
 */
export function generateGraph(
  filePath: string,
  options: GraphOptions
): {
  content: string;
  outputPath: string | null;
} {
  // Read and parse
  const content = fs.readFileSync(filePath, 'utf-8');
  const story = parseToStory(content);

  const dot = generateDot(story, options);

  // Write if output path specified
  let outputPath: string | null = null;
  if (options.output) {
    fs.writeFileSync(options.output, dot, 'utf-8');
    outputPath = options.output;
  }

  return { content: dot, outputPath };
}

/**
 * Generate DOT format string for the story graph.
 */
function generateDot(story: Story, options: GraphOptions): string {
  const nodes = story.getAllNodes();
  const edges = story.getEdges();
  const startNode = story.getStartNode();
  const rankdir = options.layout ?? 'TB';

  const title = story.meta.title ?? 'Story Graph';

  const nodeStatements = nodes.map((node) => {
    const attrs = getNodeAttributes(node, startNode?.id);
    const attrStr = Object.entries(attrs)
      .map(([k, v]) => `${k}=${v}`)
      .join(', ');
    return `  "${escapeId(node.id)}" [${attrStr}];`;
  });

  const edgeStatements = edges.map((edge) => {
    const attrs = getEdgeAttributes(edge);
    const attrStr = Object.entries(attrs)
      .map(([k, v]) => `${k}=${v}`)
      .join(', ');
    return `  "${escapeId(edge.source)}" -> "${escapeId(edge.target)}" [${attrStr}];`;
  });

  return `// ${title}
// Generated by StoryGraph CLI
digraph story {
  // Graph attributes
  rankdir=${rankdir};
  bgcolor="#1a1a2e";
  fontname="Arial";
  node [fontname="Arial", fontsize=10];
  edge [fontname="Arial", fontsize=9];

  // Nodes
${nodeStatements.join('\n')}

  // Edges
${edgeStatements.join('\n')}
}
`;
}

/**
 * Get DOT attributes for a node based on its type.
 */
function getNodeAttributes(node: StoryNode, startNodeId?: string): Record<string, string> {
  const isStart = node.id === startNodeId;
  const isEnding = node.type === 'passage' && 'ending' in node && node.ending;

  const baseAttrs: Record<string, string> = {
    label: `"${escapeLabel(node.id)}"`,
    fontcolor: '"#f0fdf4"',
  };

  // Color by type
  switch (node.type) {
    case 'passage':
      baseAttrs.shape = 'box';
      baseAttrs.style = '"rounded,filled"';
      baseAttrs.fillcolor = isStart ? '"#10b981"' : isEnding ? '"#ef4444"' : '"#1e293b"';
      baseAttrs.color = isStart || isEnding ? '"#000"' : '"#10b981"';
      if (isStart || isEnding) {
        baseAttrs.fontcolor = '"#000"';
      }
      break;

    case 'choice':
      baseAttrs.shape = 'diamond';
      baseAttrs.style = 'filled';
      baseAttrs.fillcolor = '"#1e293b"';
      baseAttrs.color = '"#3b82f6"';
      break;

    case 'condition':
      baseAttrs.shape = 'diamond';
      baseAttrs.style = 'filled';
      baseAttrs.fillcolor = '"#1e293b"';
      baseAttrs.color = '"#f59e0b"';
      break;

    case 'variable':
      baseAttrs.shape = 'ellipse';
      baseAttrs.style = 'filled';
      baseAttrs.fillcolor = '"#1e293b"';
      baseAttrs.color = '"#8b5cf6"';
      break;

    case 'include':
      baseAttrs.shape = 'box';
      baseAttrs.style = '"dashed,filled"';
      baseAttrs.fillcolor = '"#1e293b"';
      baseAttrs.color = '"#64748b"';
      break;

    case 'comment':
      baseAttrs.shape = 'note';
      baseAttrs.style = 'filled';
      baseAttrs.fillcolor = '"#334155"';
      baseAttrs.color = '"#64748b"';
      break;
  }

  return baseAttrs;
}

/**
 * Get DOT attributes for an edge based on its type.
 */
function getEdgeAttributes(edge: Edge): Record<string, string> {
  const attrs: Record<string, string> = {
    color: '"#64748b"',
    fontcolor: '"#94a3b8"',
  };

  if (edge.label) {
    attrs.label = `"${escapeLabel(edge.label)}"`;
  }

  switch (edge.type) {
    case 'choice':
      attrs.color = '"#10b981"';
      break;
    case 'condition':
      attrs.color = edge.branch === 'true' ? '"#10b981"' : '"#ef4444"';
      attrs.style = 'dashed';
      if (edge.branch) {
        attrs.label = `"${edge.branch}"`;
      }
      break;
    case 'next':
      attrs.color = '"#64748b"';
      break;
    case 'return':
      attrs.color = '"#8b5cf6"';
      attrs.style = 'dotted';
      break;
  }

  return attrs;
}

/**
 * Escape a string for use as a DOT identifier.
 */
function escapeId(id: string): string {
  return id.replace(/"/g, '\\"');
}

/**
 * Escape a string for use in a DOT label.
 */
function escapeLabel(label: string): string {
  return label.replace(/"/g, '\\"').replace(/\n/g, '\\n');
}
